---
title: "Asy_Evaluation_0618"
author: "YunranChen"
date: "6/13/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(MASS)
library(dplyr)
library(purrr)
library(tidyr)
library(reshape2)
library("forcats")
library(mvtnorm)
library("coda")
library(ggplot2)
theme_set(theme_bw())
library(MCMCpack)
library("pROC")
library(gtable)
library(grid)
library(gridExtra)
```

# read data

```{r}
rm(list=ls())

## application 
load("tsar1127_mis_notau_ID12.RData")
load("1127Y_arrN48.RData")
```

## fitted

## all.txt

```{r}
ID=12
today="1115"
pars="Code42"
burnin=1000
niter=5000

ss=(burnin+1):niter
Pi_est=pi_arr_est_cache[,ss] #samples
pi_est_pos=Pi_est%>%apply(.,1,mean) # posterior mean
pi_est_pos_arr=array(pi_est_pos,dim=c(V,V,N))
for (t in 1:N){
  diag(pi_est_pos_arr[,,t])=NA
  diag(Y_arr[,,t])=NA
}

yij_vec=Y_arr%>%as.vector(.)
auc=auc(roc(yij_vec,pi_est_pos,direction = "<"))
yij_vec_p=Y_arr[,,N]%>%as.vector(.)
auc_p=auc(roc(yij_vec_p,pi_est_pos_arr[,,N]%>%as.vector(.),direction = "<"))
pi_est_pos_arr[,,N]=NA
yij_vec_f=Y_arr%>%as.vector(.)
auc_f=auc(roc(yij_vec_f,pi_est_pos_arr%>%as.vector(.),direction = "<"))

effsize_pi=apply(Pi_est,1,function(x){effectiveSize(as.mcmc(x))})
eff_pi=c(min(effsize_pi),median(effsize_pi),mean(effsize_pi),max(effsize_pi))
mu_cache=mu_cache[,ss]
effsize_mu=apply(mu_cache,1,function(x){effectiveSize(as.mcmc(x))})
eff_mu=c(min(effsize_mu),median(effsize_mu),mean(effsize_mu),max(effsize_mu))
effsize_tau=apply(tau_cache,1,function(x){effectiveSize(as.mcmc(x))})
eff_tau=c(min(effsize_tau),median(effsize_tau),mean(effsize_tau),max(effsize_tau))
#proc_time=((future-now)/60/60/24)[3]
tau=tau_cache%>%apply(.,1,mean)
tau_inv=1/tau
cat(ID, pars, auc,auc_p,eff_pi,eff_mu,eff_tau,eff_beta1,eff_beta2,eff_a,eff_b,round(tau_inv,4),"\n", file = "application.txt", append = TRUE)
cat(ID, pars, auc_f,auc_p,auc,"\n", file = "application_auc.txt", append = TRUE)
```

## title setting

```{r}
ID=12
today="1208"
pars="Y48"
timeq=paste0(rep(2007:2010,each=4),"/",rep(c(1,4,7,10),4))
timeq_p=paste0(rep(2007:2010,each=4),"/",rep(1:12,4))
timeq_=rep("",48)
timeq_[seq(1,48,3)]=timeq
```

## histgram for pi effective sample size

```{r}
inds=(1:(V*V*N))[!is.na(pi_est_pos_arr)]
effsize_pidf=data.frame(pi=effsize_pi[inds])
histeffpi=ggplot(data = effsize_pidf,mapping = aes(pi))+geom_histogram(fill="white",color="black")+
  xlab(expression(hat(pi)[ij]))+
  #coord_equal(ratio=1)+
  theme(aspect.ratio=1)+
  #coord_fixed()+
    ggtitle("(a)")
ggsave(filename = "effsizepi51.eps",width = 8,height = 6)

```

##AUC

```{r}
pi_est_pos=Pi_est%>%apply(.,1,mean) # posterior mean
pi_est_pos_arr=array(pi_est_pos,dim=c(V,V,N))

#auc=auc(roc(yij_vec,pi_est_pos,direction = "<"))
yij_vec_p=Y_arr[,,N]%>%as.vector(.)
roc_p=roc(yij_vec_p,pi_est_pos_arr[,,N]%>%as.vector(.),direction = "<")
rocp=ggroc(data = roc_p)+coord_equal(ratio=1)+ggtitle("(c)")
ggsave(filename = "roc_p51.eps")
#auc_p=auc(roc_p)

Y_arr0=Y_arr
Y_arr0[,,N]=NA
yij_vec=Y_arr0%>%as.vector(.)
roc_a=roc(yij_vec,pi_est_pos,direction = "<")
roca=ggroc(data = roc_a)+coord_equal(ratio=1)+ggtitle("(b)")
ggsave(filename = "roc_a51.eps")
```

```{r}

gg=grid.arrange(histeffpi,roca,rocp, nrow = 1)
ggsave(filename = "abc48.eps",width = 18,height = 6,plot = gg)
```



## draw the matrix of pij(t) and difference matrix

```{r}
#timeq=paste0(rep(2007:2016),"Q",rep(1,10))
#timeq_p=paste0(rep(2007:2016,each=4),"Q",rep(1:4,10))
timeq=paste0(rep(2007:2010,each=12),"/",rep(1:12,4))
timepoint=c(1,6,12,13,18,24,25,30,36,37,42,48)
#load("top18_countries.RData")
matls=map(timepoint,function(t){
  diag(pi_est_pos_arr[,,t])=NA
  mat=pi_est_pos_arr[,,t]
  colnames(mat)=top15
  rownames(mat)=top15
  return(mat)
})
longDatae=melt(matls)%>%mutate(group="pi")

matlst=map(timepoint,function(t){
  #diag(pi_arr[,,t])=NA
  mat=Y_arr[,,t]
  colnames(mat)=top15
  rownames(mat)=top15
  return(mat)
})
longDatat=melt(matlst)%>%mutate(group="y")
longData_all=rbind(longDatae,longDatat)
longData_all=longData_all%>%mutate(Var1=fct_rev(Var1),time=timeq[timepoint][L1])
longData_all=longData_all%>%mutate(time=factor(time,levels= paste0(rep(2007:2010,each=3),"/",rep(c(1,6,12),4))))


  
  #jpeg(filename=paste0("Setting",pars,"_TASKID",ID,"_pi",t,"_0702.jpeg"))
gp_piij=ggplot(longData_all, aes(x = Var2, y = Var1)) + 
  geom_tile(aes(fill=value)) + facet_grid(group~time )+
  scale_fill_gradient2( low="blue", mid="white",high="red", space ="Lab" )+
  theme_bw() + theme(axis.text.x=element_blank(),#element_text(size=9, angle=90, vjust=0.3),
    #axis.text.x = element_text(angle = 90, hjust = 1),
                     #axis.text.y=element_blank(),#element_text(size=9),
                     plot.title=element_text(size=11))+ggtitle("")+xlab("")+ylab("")+
  guides(fill = guide_colourbar(barheight = 15))

ggsave(filename = "matpi48.eps",scale = 1,width = 16,height = 3.5)
#dev.print(pdf, paste0(today,"_",pars,"_TASKID",ID,"_matpigrey",".pdf"))

gp_piij=ggplot(longData_all%>%filter(group=="y"), aes(x = Var2, y = Var1)) + 
  geom_tile(aes(fill=value)) + facet_wrap(~time,nrow = 2,)+
  scale_fill_gradient2( low="blue", mid="white",high="red", space ="Lab" )+
  theme_bw() + theme(axis.text.x=element_blank(),#element_text(size=9, angle=90, vjust=0.3),
    #axis.text.x = element_text(angle = 90, hjust = 1),
                     #axis.text.y=element_blank(),#element_text(size=9),
                     plot.title=element_text(size=11))+ggtitle("")+xlab("")+ylab("")+
  guides(fill = guide_colourbar(barheight = 15))

ggsave(filename = "ts.eps",scale = 1,width = 12,height = 4)

```


# mu(t)

```{r}
ci_mu=HPDinterval(as.mcmc(t(mu_cache)), prob=0.95)
ci_mu=ci_mu%>%as_tibble()
time = 1:N
mu_ggdf=data_frame(time=time,estimate=apply(mu_cache,1,mean),lower=ci_mu%>%pull(lower),upper=ci_mu%>%pull(upper))%>%mutate(group="mu")


pmut=ggplot(mu_ggdf, aes(x=time))+geom_ribbon(aes(ymin=lower,ymax=upper),fill=gray(0.9))+ylab(expression(mu[t]))+geom_line(mapping = aes(y=estimate))+ggtitle("")+
  scale_x_continuous(breaks=seq(1,48,3),minor_breaks = seq(1,48,1) ,labels = timeq)#+ 
  #theme(axis.text.x = element_text(angle = 90, hjust = 1))
ggsave(filename = "mut48.eps",width = 10,height = 4)


```


## pij-i,pij-j, pij(t)

```{r}
## Japan
j=8

a_pos=pi_est_pos_arr[j,,]
colnames(a_pos)=paste0("t",1:N)
rownames(a_pos)=top15
a_pos[j,]=NA
longData=melt(a_pos)
  longData_all=as_tibble(longData)
  longData_all1=longData_all%>%mutate(Var1=fct_rev(Var1))

ppiji=ggplot(longData_all1, aes(x = Var2, y = Var1)) + 
  geom_tile(aes(fill=value)) + 
  scale_fill_gradient2( low="blue", mid="white",high="red", space ="Lab" )+
  #scale_fill_gradient(low="white", high="#333333",na.value = "black") + 
  theme_bw() + theme(#axis.text.x=element_blank(),#element_text(size=9, angle=90, vjust=0.3),
    #axis.text.x = element_text(angle = 90, hjust = 1),
                     #axis.text.y=element_blank(),#element_text(size=9),
                     plot.title=element_text(size=11))+ggtitle("")+xlab("")+ylab("")+
  guides(fill = guide_colourbar(barheight = 15))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  scale_x_discrete(labels=timeq_)+ guides(fill=FALSE)+ggtitle(paste0("(f)",top15[j]))


ci=HPDinterval(as.mcmc(t(Pi_est)), prob=0.95)
ci=ci%>%as_tibble()
pi_ggdf=data_frame(row=rep(1:V,V*N),col=rep(rep(1:V,each=V),N),time=rep(1:N,each=V*V),estimate=apply(Pi_est,1,mean),lower=ci%>%pull(lower),upper=ci%>%pull(upper))

i=8
j=5
piij_ggdf=pi_ggdf%>%
  dplyr::filter(row==i,col==j)%>%
  dplyr::select(.,-row,-col)%>%
  mutate(group="pi",y=Y_arr[i,j,])
ppij49=ggplot(piij_ggdf, aes(x=time))+geom_ribbon(aes(ymin=lower,ymax=upper),fill=gray(0.9))+ylab(expression(pi[t]))+geom_line(mapping = aes(y=estimate))+ggtitle(paste0("(g)",top15[j]))+
  geom_point(mapping = aes(y=y))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  scale_x_continuous(breaks=seq(1,48,3),minor_breaks = seq(1,48,1) ,labels = timeq)#


j=6
piij_ggdf=pi_ggdf%>%
  dplyr::filter(row==i,col==j)%>%
  dplyr::select(.,-row,-col)%>%
  mutate(group="pi",y=Y_arr[i,j,])
ppij411=ggplot(piij_ggdf, aes(x=time))+geom_ribbon(aes(ymin=lower,ymax=upper),fill=gray(0.9))+ylab(expression(pi[t]))+geom_line(mapping = aes(y=estimate))+ggtitle(paste0("(h)",top15[j]))+
  geom_point(mapping = aes(y=y))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  scale_x_continuous(breaks=seq(1,48,3),minor_breaks = seq(1,48,1) ,labels = timeq)#

j=11
piij_ggdf=pi_ggdf%>%
  dplyr::filter(row==i,col==j)%>%
  dplyr::select(.,-row,-col)%>%
  mutate(group="pi",y=Y_arr[i,j,])
ppij412=ggplot(piij_ggdf, aes(x=time))+geom_ribbon(aes(ymin=lower,ymax=upper),fill=gray(0.9))+ylab(expression(pi[t]))+geom_line(mapping = aes(y=estimate))+ggtitle(paste0("(i)",top15[j]))+
  geom_point(mapping = aes(y=y))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  scale_x_continuous(breaks=seq(1,48,3),minor_breaks = seq(1,48,1) ,labels = timeq)#


j=14
piij_ggdf=pi_ggdf%>%
  dplyr::filter(row==i,col==j)%>%
  dplyr::select(.,-row,-col)%>%
  mutate(group="pi",y=Y_arr[i,j,])
ppij415=ggplot(piij_ggdf, aes(x=time))+geom_ribbon(aes(ymin=lower,ymax=upper),fill=gray(0.9))+ylab(expression(pi[t]))+geom_line(mapping = aes(y=estimate))+ggtitle(paste0("(j)",top15[j]))+
  geom_point(mapping = aes(y=y))+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  scale_x_continuous(breaks=seq(1,48,3),minor_breaks = seq(1,48,1) ,labels = timeq)#


gg=grid.arrange(ppiji,ppij49,ppij411,ppij412,ppij415, nrow = 1,ncol=5)
#gg1=gg
ggnew=grid.arrange(gg1,gg,nrow=2,ncol=1)
ggsave(filename = "pinew.pdf",width = 18,height = 6,plot = ggnew)

```


## save all plots

```{r}
save(histeffpi51=histeffpi,rocp51=rocp,roca51=roca,gp_piij51=gp_piij,pmut51=pmut,pbetat1_51=pbetat1,pbetat2_51=pbetat2,ppiji51=ppiji,ppijj51=ppijj,ppijij51=ppijij,ppij139_51=ppij139,ppij913_51=ppij913,pab51=pab,pat51=pat,pbt51=pbt,file = "code51_plots.RData")
save.image("code41H10Res1117.RData")
```


## output to a txt file

```{r}
cat(ID, pars, auc,auc_p,eff_pi,eff_mu,eff_tau,eff_beta,eff_a,eff_b, round(proc_time,4),round(tau_inv,4),"\n", file = "all.txt", append = TRUE)

```

